print("Nether Ore Finder: Slave install")
shell.run("delete slavecode")
shell.run("delete state.cc")
shell.run("delete startup")
shell.run("delete reset")
shell.run("rom/programs/http/pastebin get tD0XGhGD slavecode")
shell.run("rom/programs/http/pastebin get TLfhLDdS startup")
shell.run("rom/programs/http/pastebin get G6RD2x2G reset")
print("Done!")
